<a href="https://colab.research.google.com/github/RafaelCardoso140701/Projetos-Data-Science/blob/main/Deploy_do_modelo___Arquivo_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fazendo o deploy do nosso modelo

### Regressão no Scikit-Learn
- https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
<br><br>
- Vamos usar o dataset de preço das casas na Califórnia
    - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html#sklearn.datasets.fetch_california_housing
    - Esse dataset já está foi separado nos arquivos `casas_treino.csv` e `casas_teste.csv` utilizando o train_test_split com os parâmetros test_size=0.33 e random_state=42

In [1]:
# Importando o pandas
import pandas as pd

In [2]:
# Importando a base de treino
treino = pd.read_csv('casas_treino.csv')
treino = treino.drop('Unnamed: 0',axis=1)

In [3]:
# Visualizando as 3 primeiras linhas
treino.head(3)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,0.9809,19.0,3.187726,1.129964,726.0,2.620939,33.98,-118.28,1.214
1,4.2232,33.0,6.189696,1.086651,1015.0,2.377049,37.46,-122.23,3.637
2,3.5488,42.0,4.821577,1.095436,1044.0,4.331950,33.79,-118.26,2.056

In [4]:
# Separando X e y
X = treino.drop('MedHouseVal',axis=1)
y = treino.MedHouseVal

### Usando o modelo de regressão linear

In [5]:
# Importando a Regressão Linear
from sklearn.linear_model import LinearRegression

In [6]:
# Criando nosso algoritmo de regressão
reg = LinearRegression().fit(X, y)

In [7]:
# Avaliando o modelo nos dados de TESTE usando apenas o score
teste = pd.read_csv('casas_teste.csv')
teste = teste.drop('Unnamed: 0',axis=1)

# Separando X e y
X_teste = teste.drop('MedHouseVal',axis=1)
y_teste = teste.MedHouseVal

reg.score(X_teste, y_teste)

0.5970494128783954

In [8]:
# Exibindo o intercept
reg.intercept_

np.float64(-37.08201093907984)

In [9]:
# Exibindo o coef
reg.coef_

array([ 4.44870466e-01,  9.55004561e-03, -1.21991503e-01,  7.79144696e-01,
       -7.68990809e-08, -3.29948505e-03, -4.19131153e-01, -4.34103468e-01])

In [10]:
teste.head(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,1.6812,25.0,4.192201,1.022284,1392.0,3.877437,36.06,-119.01,0.477
1,2.5313,30.0,5.039384,1.193493,1565.0,2.679795,35.14,-119.46,0.458

### Persistência do modelo

In [11]:
# Fazendo o dump do nosso modelo
from joblib import dump
dump(reg, 'regressao.joblib')

['regressao.joblib']